### ISSUE TITLE
LOG_STDOUT does not work

### ISSUE THREAD

**Issue by ricardogsilva** [million12/docker-vsftpd#2]
When trying to set the `-e LOG_STDOUT=true` environment variable, the docker container fails with 

```bash
/usr/bin/ln: failed to create symbolic link '/var/log/vsftpd/vsftpd.log': No such file or directory
```

My full docker run command:

```bash
docker run \
    --init \
    --rm \
    -e FTP_USER=testftp \
    -e FTP_PASS=testftp \
    -e ANONYMOUS_ACCESS=true \
    -p 8020-8021:20-21 \
    -p 21100-21110:21100-21110 \
    -v $HOME/test_data/ftp_test:/home/vsftpd \
    -e LOG_STDOUT=true \
    million12/vsftpd
```

If I run this same command without setting the `LOG_STDOUT` variable everything works fine. I'm running  `Docker version 17.05.0-ce, build 89658be`

**Comment by pozgo** [comment]
Thats for spotting it 

Fixed with commit [5f80c31df94888f609d8a7d159dd889600b80b94](https://github.com/million12/docker-vsftpd/commit/5f80c31df94888f609d8a7d159dd889600b80b94)

**Comment by ricardogsilva** [comment]
@pozgo this is not fixed, please reopen.

The original error is gone and the container can now be run. However, the logs are being stored in `/var/log/vsftpd.log` and not in `/var/log/vsftpd/vsftpd.log` as expected. It seems to me that the `vsftpd_log_file` parameter is missing from `vsftpd.conf` 

https://security.appspot.com/vsftpd/vsftpd_conf.html

**Comment by charMstr** [comment]
@ricardogsilva is rigth:
the logs by default go into **/var/log/vsftpd.log** and **NOT** into **/var/log/vsftpd/vsftpd.log**, as stated in the default vsftpd.conf file:

> #You may override where the log file goes if you like. The default is shown
> #below.
> #xferlog_file=/var/log/vsftpd.log


and each time i try to tie this log file to stdout like so while building my own docker image: 
`RUN ln -sf /dev/stdout /var/log/vsftpd.log`
i get the same problem happening, and the error message from a client is:

> 500 OOPS: failed to open vsftpd log file:/var/log/vsftpd.log

(same message with 2 different clients: filezilla and lftp)

while inside the container, just deleting the symlink goes back to normal. By that i mean no more error message, and the /var/log/vsftpd.log file is created automatically upon next connexion, but i still can't pass on those logs to docker.

anyone has an idea?

**Comment by pozgo** [comment]
Thanks for the info. I'll have a look when I have some spare time on my hands.

**Comment by charMstr** [comment]
Great fix, thanks.
I did not think of the "tail -f" solution.
I just implemented it on my side, and it seems to be perfectly working
without the pipe and the "tee" command though.

Regards.
